t

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -144,3 +144,31 @@ jobs:
             echo "Expected step to fail"
             exit 1
           fi
+
+      - name: '[Run] Negative test: always-comment w/o github-token'
+        if: always() && steps.pre-setup.outcome == 'success'
+        uses: ./
+        with:
+          image: ${{ env.TEST_IMAGE }}
+          always-comment: true
+
+      - name: '[Verification] Negative test: always-comment w/o github-token'
+        # It will not be able to create comment outside PR. result in main branch:
+        # Not Found - https://docs.github.com/rest
+        if: always() && steps.pre-setup.outcome == 'success' && github.ref !=
+          'refs/heads/main'
+        shell: bash
+        run: |
+          error_message="${{ steps.missing-required.outputs.error }}"
+          expected_message="Resource not accessible by integration - \
+          https://docs.github.com/rest/issues/comments#create-an-issue-comment"
+
+          if [[ ! "$error_message" =~ "$expected_message" ]]; then
+            echo "Expected error message to contain: $expected_message"
+            echo "Got: $error_message"
+            exit 1
+          fi
+          if [[ "${{ steps.missing-required.outcome }}" != "failure" ]]; then
+            echo "Expected step to fail"
+            exit 1
+          fi
